// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The Prisma CLI (migrate / db pull) uses a DIRECT connection.
    // On Supabase that's the session/direct connection on port 5432 (DIRECT_URL).
    // Falls back to DATABASE_URL for simple single-connection setups.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
